# -*- coding: utf-8 -*-
"""proj_amazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWYNMTXRkJ2zSUeFb2JKC-Iybm2bGebr
"""

!pip install -q datasets

from datasets import load_dataset
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

dataset = load_dataset(
    "PJ2005/amazon-fine-food-reviews",
    split="train"
)

dataset = load_dataset(
    "PJ2005/amazon-fine-food-reviews",
    split="train",
    streaming=True
)

dataset = dataset.shuffle(
    seed=42,
    buffer_size=10_000
)

small_dataset = dataset.take(50_000)

df = pd.DataFrame(list(small_dataset))

df.shape
df.columns

df.head()
df.info()
df.shape

df["Score"].value_counts().sort_index()

df.isnull().sum()

df.head()

print(df["Text"].iloc[0])

df.dtypes

df.info()

df.isnull().sum()

df["Score"].value_counts().sort_index()

score_distribution = (
    df["Score"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

score_distribution

df["Score"].value_counts().sort_index().plot(
    kind="bar"
)

plt.xlabel("Score")
plt.ylabel("Number of Reviews")
plt.title("Distribution of Review Scores")
plt.show()

df["word_count"] = df["Text"].fillna("").str.split().str.len()

df["word_count"].describe()

df.loc[df["word_count"].idxmax(), "Text"]

df.isnull().sum()

missing_percentage = (
    df.isnull().mean() * 100
)

missing_percentage.sort_values(ascending=False)

df["Text"].isnull().sum()

df = df.dropna(subset=["Text"]).copy()

print("Missing Text:", df["Text"].isnull().sum())
print("New shape:", df.shape)

df.duplicated().sum()

df[df.duplicated()].head()

df = df.drop_duplicates().copy()

df[df["Text"].duplicated(keep=False)] \
    .sort_values("Text")[["Text", "Score"]] \
    .head(20)

empty_text = df["Text"].str.strip().eq("").sum()
print("Empty or whitespace-only reviews:", empty_text)

df = df[df["Text"].str.strip().ne("")].copy()

df["Score"].unique()

df["Score"].value_counts().sort_index()

invalid_scores = df[
    ~df["Score"].between(1, 5)
]

print("Invalid score rows:", len(invalid_scores))

invalid_helpfulness = df[
    df["HelpfulnessNumerator"] > df["HelpfulnessDenominator"]
]

print("Invalid helpfulness rows:", len(invalid_helpfulness))

invalid_helpfulness = df[
    df["HelpfulnessNumerator"] > df["HelpfulnessDenominator"]
]

print("Invalid helpfulness rows:", len(invalid_helpfulness))

df["Date"] = pd.to_datetime(
    df["Time"],
    unit="s"
)

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month

def create_sentiment(score):
    if score <= 2:
        return "Negative"
    elif score == 3:
        return "Neutral"
    else:
        return "Positive"


df["Sentiment"] = df["Score"].apply(create_sentiment)

df[["Score", "Sentiment"]].head(20)

df["Sentiment"].value_counts()

df["Sentiment"].value_counts(normalize=True).mul(100).round(2)

df["Sentiment"].value_counts().plot(
    kind="bar"
)

plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.title("Sentiment Distribution")
plt.xticks(rotation=0)
plt.show()

print("Final shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nSentiment distribution:")
print(df["Sentiment"].value_counts())

df["ProfileName"] = df["ProfileName"].fillna("Anonymous")
df["Summary"] = df["Summary"].fillna("No Summary")

df.isnull().sum()

df["Sentiment"].value_counts()
df["Sentiment"].value_counts(normalize=True).mul(100).round(2)

import matplotlib.pyplot as plt

df["Sentiment"].value_counts().plot(
    kind="bar",
    figsize=(7, 4)
)

plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.title("Sentiment Distribution")
plt.xticks(rotation=0)
plt.show()

df.groupby("Sentiment")["word_count"].mean()
df.groupby("Sentiment")["word_count"].median()

pd.crosstab(
    df["Score"],
    df["Sentiment"]
)

pd.crosstab(
    df["Score"],
    df["Sentiment"]
)

df.loc[
    df["word_count"].idxmax(),
    ["Score", "Sentiment", "word_count", "Text"]
]

df.loc[
    df["word_count"].idxmin(),
    ["Score", "Sentiment", "word_count", "Text"]
]

plt.figure(figsize=(8, 5))

df["word_count"].plot(
    kind="hist",
    bins=50
)

plt.xlabel("Number of Words")
plt.ylabel("Frequency")
plt.title("Distribution of Review Length")
plt.show()

df.duplicated().sum()

invalid_helpfulness = (
    df["HelpfulnessNumerator"] >
    df["HelpfulnessDenominator"]
)

invalid_helpfulness.sum()

def score_to_sentiment(score):
    if score <= 2:
        return "Negative"
    elif score == 3:
        return "Neutral"
    else:
        return "Positive"

df["Sentiment"] = df["Score"].apply(score_to_sentiment)

df["Sentiment"] = df["Score"].apply(score_to_sentiment)

df[["Score", "Sentiment"]].head(10)

df[["Text", "Sentiment"]].head(50)

X = df["Text"]
y = df["Sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("\nTrain distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest distribution:")
print(y_test.value_counts(normalize=True))

positive_baseline = y_test.value_counts(normalize=True)["Positive"]

print(f"Baseline Accuracy: {positive_baseline:.4f}")
print(f"Baseline Accuracy: {positive_baseline * 100:.2f}%")

class_weight="balanced"

tfidf = TfidfVectorizer(
    lowercase=False,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print("Train shape:", X_train_tfidf.shape)
print("Test shape:", X_test_tfidf.shape)

print("Vocabulary size:", len(tfidf.vocabulary_))

feature_names = tfidf.get_feature_names_out()

print(feature_names[:30])

LogisticRegression(class_weight="balanced")

tfidf = TfidfVectorizer(
    lowercase=False,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print("Train shape:", X_train_tfidf.shape)
print("Test shape:", X_test_tfidf.shape)

print("Vocabulary size:", len(tfidf.vocabulary_))

logistic_model = LogisticRegression(
    class_weight="balanced",
    max_iter=1000,
    solver="saga",
    random_state=42
)

logistic_model.fit(
    X_train_tfidf,
    y_train
)

y_pred = logistic_model.predict(X_test_tfidf)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=["Negative", "Neutral", "Positive"]
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Negative", "Neutral", "Positive"]
)

disp.plot()

plt.title("Logistic Regression - Confusion Matrix")
plt.show()

nb_model = MultinomialNB()

nb_model.fit(
    X_train_tfidf,
    y_train
)

nb_pred = nb_model.predict(X_test_tfidf)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, nb_pred))

print("\nClassification Report:")
print(classification_report(y_test, nb_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm_nb = confusion_matrix(
    y_test,
    nb_pred,
    labels=["Negative", "Neutral", "Positive"]
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_nb,
    display_labels=["Negative", "Neutral", "Positive"]
)

disp.plot()

plt.title("Multinomial Naive Bayes - Confusion Matrix")
plt.show()

svm_model = LinearSVC(
    class_weight="balanced",
    C=1.0,
    random_state=420
)

svm_model.fit(
    X_train_tfidf,
    y_train
)

svm_pred = svm_model.predict(X_test_tfidf)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, svm_pred))

print("\nClassification Report:")
print(classification_report(y_test, svm_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm_svm = confusion_matrix(
    y_test,
    svm_pred,
    labels=["Negative", "Neutral", "Positive"]
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_svm,
    display_labels=["Negative", "Neutral", "Positive"]
)

disp.plot()

plt.title("Linear SVM - Confusion Matrix")
plt.show()

results = {
    "Logistic Regression": {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Macro F1": 0.66,
        "Weighted F1": 0.83
    },
    "Naive Bayes": {
        "Accuracy": accuracy_score(y_test, nb_pred),
        "Macro F1": 0.29,
        "Weighted F1": 0.67
    },
    "Linear SVM": {
        "Accuracy": accuracy_score(y_test, svm_pred),
        "Macro F1": 0.71,
        "Weighted F1": 0.87
    }
}

comparison_df = pd.DataFrame(results).T
comparison_df

from sklearn.metrics import accuracy_score, f1_score

results = {
    "Logistic Regression": {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Macro F1": f1_score(y_test, y_pred, average="macro"),
        "Weighted F1": f1_score(y_test, y_pred, average="weighted")
    },
    "Naive Bayes": {
        "Accuracy": accuracy_score(y_test, nb_pred),
        "Macro F1": f1_score(y_test, nb_pred, average="macro"),
        "Weighted F1": f1_score(y_test, nb_pred, average="weighted")
    },
    "Linear SVM": {
        "Accuracy": accuracy_score(y_test, svm_pred),
        "Macro F1": f1_score(y_test, svm_pred, average="macro"),
        "Weighted F1": f1_score(y_test, svm_pred, average="weighted")
    }
}

comparison_df = pd.DataFrame(results).T

print(comparison_df)

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=False,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )),

    ("svm", LinearSVC(
        class_weight="balanced",
        random_state=42
    ))
])

param_grid = {
    "svm__C": [0.1, 0.5, 1, 2, 5]
}

grid_search = GridSearchCV(
    pipeline,
    param_grid,
    scoring="f1_macro",
    cv=3,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(
    X_train,
    y_train
)

print("Best Parameters:")
print(grid_search.best_params_)

best_svm = grid_search.best_estimator_

final_pred = best_svm.predict(X_test)

print(classification_report(
    y_test,
    final_pred
))

final_accuracy = accuracy_score(
    y_test,
    final_pred
)

final_macro_f1 = f1_score(
    y_test,
    final_pred,
    average="macro"
)

final_weighted_f1 = f1_score(
    y_test,
    final_pred,
    average="weighted"
)

print("Final Accuracy:", final_accuracy)
print("Final Macro F1:", final_macro_f1)
print("Final Weighted F1:", final_weighted_f1)

print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest CV Macro F1:")
print(grid_search.best_score_)

print(classification_report(
    y_test,
    final_pred
))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm_final = confusion_matrix(
    y_test,
    final_pred,
    labels=["Negative", "Neutral", "Positive"]
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_final,
    display_labels=["Negative", "Neutral", "Positive"]
)

disp.plot()

plt.title("Final Tuned Linear SVM - Confusion Matrix")
plt.show()

final_results = {
    "Logistic Regression": {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Macro F1": f1_score(y_test, y_pred, average="macro"),
        "Weighted F1": f1_score(y_test, y_pred, average="weighted")
    },

    "Naive Bayes": {
        "Accuracy": accuracy_score(y_test, nb_pred),
        "Macro F1": f1_score(y_test, nb_pred, average="macro"),
        "Weighted F1": f1_score(y_test, nb_pred, average="weighted")
    },

    "Linear SVM": {
        "Accuracy": accuracy_score(y_test, svm_pred),
        "Macro F1": f1_score(y_test, svm_pred, average="macro"),
        "Weighted F1": f1_score(y_test, svm_pred, average="weighted")
    },

    "Tuned Linear SVM": {
        "Accuracy": accuracy_score(y_test, final_pred),
        "Macro F1": f1_score(y_test, final_pred, average="macro"),
        "Weighted F1": f1_score(y_test, final_pred, average="weighted")
    }
}

final_comparison = pd.DataFrame(final_results).T
final_comparison

import joblib

joblib.dump(
    best_svm,
    "sentiment_svm_pipeline.pkl"
)

import os

print(os.path.getsize("sentiment_svm_pipeline.pkl") / (1024 * 1024), "MB")

!pip install gradio -q

import joblib

loaded_pipeline = joblib.load("sentiment_svm_pipeline.pkl")

def predict_sentiment_ui(review_text):
    if not review_text.strip():
        return "Please write a review first"

    prediction = loaded_pipeline.predict([review_text])[0]
    return f"Predicted Sentiment: {prediction}"

import gradio as gr

demo = gr.Interface(
    fn=predict_sentiment_ui,
    inputs=gr.Textbox(
        lines=5,
        placeholder="Write your review here...",
        label="Review Text"
    ),
    outputs=gr.Textbox(label="Prediction Result"),
    title="Sentiment Analysis - Amazon Fine Food Reviews",
    description="Write a review about any food product, and the model will predict whether it's Positive, Negative, or Neutral",
    examples=[
        ["This product is amazing, I love it so much!"],
        ["Terrible quality, broke after one day, waste of money."],
        ["It's okay, nothing special but does the job."]
    ]
)

neutral_errors = pd.DataFrame({
    "Text": X_test,
    "True": y_test,
    "Predicted": final_pred
})

neutral_errors = neutral_errors[
    (neutral_errors["True"] == "Neutral") &
    (neutral_errors["Predicted"] != "Neutral")
]

neutral_errors.head(20)

class_weight="balanced"
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=False,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )),
    ("svm", LinearSVC(
        random_state=42
    ))
])

param_grid = {
    "svm__C": [0.5, 1, 2, 5],
    "svm__class_weight": [
        "balanced",
        {
            "Negative": 1.0,
            "Neutral": 2.0,
            "Positive": 1.0
        },
        {
            "Negative": 1.0,
            "Neutral": 3.0,
            "Positive": 1.0
        }
    ]
}

grid_search = GridSearchCV(
    pipeline,
    param_grid,
    scoring="f1_macro",
    cv=3,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

best_svm = grid_search.best_estimator_
final_pred = best_svm.predict(X_test)

print("Best Parameters:", grid_search.best_params_)
print("Accuracy:", accuracy_score(y_test, final_pred))
print("Macro F1:", f1_score(y_test, final_pred, average="macro"))
print("Weighted F1:", f1_score(y_test, final_pred, average="weighted"))

svd = TruncatedSVD(n_components=100, random_state=42)

X_train_svd = svd.fit_transform(X_train_tfidf)

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_train_svd)

silhouette = silhouette_score(X_train_svd, clusters)

print("Silhouette Score:", silhouette)

demo.launch(debug=True)